SourBlog/SourBlogUI/Controllers/HeadingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.Repositories;
using EntityLayer.Concrete;

namespace SourBlogUI.Controllers
{
    public class HeadingController : Controller
    {
        private readonly IHeadingService _headingService = new HeadingManager(new EfHeadingDal());
        private readonly ICategoryService _categoryService = new CategoryManager(new EfCategoryDal());
        private readonly IWriterService _writerService = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var headings = _headingService.List().Where(x=>x.HeadingStatus==true);
            return View(headings);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> categories = (from item in _categoryService.List()
                                               select new SelectListItem()
                                               {
                                                   Value = item.CategoryId.ToString(),
                                                   Text = item.CategoryName
                                               }).ToList();
            ViewBag.Categories = categories;
            List<SelectListItem> writers = (from item in _writerService.List()
                                            select new SelectListItem()
                                            {
                                                Text = item.WriterName + " " + item.WriterSurname,
                                                Value = item.WriterId.ToString()
                                            }).ToList();
            ViewBag.Writers = writers;

            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            heading.HeadingStatus = true;
            _headingService.Insert(heading);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var heading = _headingService.GetById(id);
            heading.HeadingStatus = false;
            _headingService.Update(heading);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateHeading(int id)
        {
            List<SelectListItem> categories = (from item in _categoryService.List()
                select new SelectListItem()
                {
                    Value = item.CategoryId.ToString(),
                    Text = item.CategoryName
                }).ToList();
            ViewBag.Categories = categories;

            var heading = _headingService.GetById(id);
            return View(heading);
        }

        [HttpPost]
        public ActionResult UpdateHeading(Heading heading)
        {
            heading.HeadingStatus = true;
            _headingService.Update(heading);
            return RedirectToAction("Index");
        }
    }
}

SourBlog/SourBlogUI/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
    {
        <label>Heading Title</label>
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName, "", new { @style = "color:red" })
        <br />
        <label>Heading Category</label>
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.Categories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId, "", new { @style = "color:red" })
        <br />
        <label>Heading Creator</label>
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.Writers, new { @class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterId, "", new { @style = "color:red" })
        <br />
        <button class="btn btn-primary">Add Heading</button>
    }
</div>

SourBlog/SourBlogUI/Views/Heading/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Headings Page</h1>
                    <a href="/Heading/AddHeading/" class="btn btn-outline-success mt-2">Add Heading</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Title Management</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects text-center">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Title
                            </th>
                            <th style="width: 30%">
                                Creator
                            </th>
                            <th style="width: 8%" class="text-center">
                                Category
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.HeadingDate.ToShortDateString()
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <span class="badge badge-success">@item.Writer.WriterName @item.Writer.WriterSurname</span>
                                            <img alt="Avatar" class="table-avatar" style="width:100px; height:100px" src=@item.Writer.WriterImage>
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <h5><span class="badge badge-success">@item.Category.CategoryName</span></h5>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Contents
                                    </a>
                                    <a class="btn btn-warning btn-sm" href="/Heading/UpdateHeading/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Update
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>

SourBlog/SourBlogUI/Views/Heading/UpdateHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "UpdateHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("UpdateHeading", "Heading", FormMethod.Post))
    {
        @Html.HiddenFor(x=>x.HeadingDate)
        @Html.HiddenFor(x=>x.HeadingId)
        @Html.HiddenFor(x=>x.WriterId)
        <label>Heading Title</label>
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName, "", new { @style = "color:red" })
        <br />
        <label>Heading Category</label>
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.Categories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId, "", new { @style = "color:red" })
        <br />
        <button class="btn btn-success">Update Heading</button>
    }
</div>