SourBlog/SourBlogUI/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Abstract;
using DataAccessLayer.Concrete.Repositories;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace SourBlogUI.Controllers
{
    public class WriterController : Controller
    {
        private readonly IWriterService _writerService = new WriterManager(new EfWriterDal());
        private readonly WriterValidator _writerValidator = new WriterValidator();

        public ActionResult Index()
        {
            var writers = _writerService.List().Where(x=>x.WriterStatus==true);
            return View(writers);
        }

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddWriter(Writer writer)
        {
            
            ValidationResult validationResult = _writerValidator.Validate(writer);
            if (validationResult.IsValid)
            {
                _writerService.Insert(writer);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

                return View();
            }
        }

        [HttpGet]
        public ActionResult UpdateWriter(int id)
        {
            var writer = _writerService.GetById(id);
            return View(writer);
        }

        [HttpPost]
        public ActionResult UpdateWriter(Writer writer)
        {
            ValidationResult validationResult = _writerValidator.Validate(writer);
            if (validationResult.IsValid)
            {
                _writerService.Update(writer);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

                return View();
            }
        }

        public ActionResult DeleteWriter(int id)
        {
            var writer = _writerService.GetById(id);
            writer.WriterStatus = false;
            _writerService.Update(writer);
            return RedirectToAction("Index");
        }
    }
}

SourBlog/SourBlogUI/Views/Writer/AddWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post))
    {
        <label>Writer Name</label>
        @Html.TextBoxFor(x=>x.WriterName, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterName,"", new{@style="color:red"})
        <br/>
        <label>Writer Surname</label>
        @Html.TextBoxFor(x=>x.WriterSurname, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterSurname,"", new{@style="color:red"})
        <br/>
        <label>Writer Mail</label>
        @Html.TextBoxFor(x=>x.WriterMail, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterMail,"", new{@style="color:red"})
        <br/>
        <label>Writer About</label>
        @Html.TextAreaFor(x=>x.WriterAbout, new{@class="form-control", rows="2"})
        @Html.ValidationMessageFor(x=>x.WriterAbout,"", new{@style="color:red"})
        <br/>
        <label>Writer Title</label>
        @Html.TextBoxFor(x=>x.WriterTitle, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterTitle,"", new{@style="color:red"})
        <br/>
        <label>Writer Password</label>
        @Html.TextBoxFor(x=>x.WriterPassword, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterPassword,"", new{@style="color:red"})
        <br/>
        <label>Writer Image Url</label>
        @Html.TextBoxFor(x=>x.WriterImage, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterImage,"", new{@style="color:red"})
        <br/>
        <button class="btn btn-primary">Add Writer</button>
    }
</div>

SourBlog/SourBlogUI/Views/Writer/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Writers Page</h1>
                    <a href="/Writer/AddWriter/"class="btn btn-outline-success mt-2">Add Writer</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    @item.WriterTitle
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.WriterName @item.WriterSurname</b></h2>
                                            <p class="text-muted text-sm"><b>About: </b>@item.WriterAbout</p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-md fa-phone"></i></span> Mail: @item.WriterMail</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="@item.WriterImage" alt="" class="img-circle img-fluid" style="width:200px; height:130px">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Writer/DeleteWriter/@item.WriterId" class="btn btn-sm btn-danger">
                                            <i class="fas fa-trash"></i> Delete Profile
                                        </a>
                                        <a href="/Writer/UpdateWriter/@item.WriterId" class="btn btn-sm btn-warning">
                                            <i class="fas fa-user"></i> Update Profile
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
<!-- /.content -->
</body>

SourBlog/SourBlogUI/Views/Writer/UpdateWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "UpdateWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("UpdateWriter", "Writer", FormMethod.Post))
    {
        @Html.HiddenFor(x=>x.WriterId)
        <label>Writer Name</label>
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName, "", new { @style = "color:red" })
        <br />
        <label>Writer Surname</label>
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname, "", new { @style = "color:red" })
        <br />
        <label>Writer Mail</label>
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail, "", new { @style = "color:red" })
        <br />
        <label>Writer About</label>
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control", rows = "2" })
        @Html.ValidationMessageFor(x => x.WriterAbout, "", new { @style = "color:red" })
        <br />
        <label>Writer Title</label>
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle, "", new { @style = "color:red" })
        <br />
        <label>Writer Password</label>
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @style = "color:red" })
        <br />
        <label>Writer Image Url</label>
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage, "", new { @style = "color:red" })
        <br />
        <button class="btn btn-primary">Update</button>
    }
</div>